<?php echo "<?php"; ?>

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

/**
 * Class {!! $className !!}
 *
 * Generated by vi-kon/db-exporter
 *
 * @author Kovács Vince <vincekovacs@hotmail.com>
 */
class {!! $className !!} extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('{!! $tableName !!}', function(Blueprint $table) {
            // Add table columns
            {!! trim($_indent($columns, 12)) !!}

            // Add indexes
            {!! trim($_indent($indexes,12)) !!}

            // Add foreign keys
            {!! trim($_indent($foreignKeys, 12)) !!}
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('{!! $tableName !!}');
    }
}